#!/bin/sh


# create dirs
install -d -m 750 -u proxy -g proxy /var/cache/squid-deb-proxy
install -d -m 750 -u proxy -g proxy /var/log/squid-deb-proxy/

# create swap dirs
if [ ! -d /var/cache/squid-deb-proxy/00 ]; then
   squid -z -f /etc/squid-deb-proxy/squid-deb-proxy.conf
fi

# start it
squid -f /etc/squid-deb-proxy/squid-deb-proxy.conf